### ISSUE TITLE
[master] before all hook fails

### ISSUE THREAD

**Issue by zoepage** [gr2m/smartdate-input#13]
@gr2m the npm test fails in the master.
(JAVA is installed. It SHOULD work ;) )

````
1) "before all" hook

  0 passing (19ms)
  1 failing

  1)  "before all" hook:
     Uncaught Error: connect ECONNREFUSED
      at exports._errnoException (util.js:746:11)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)
````

**Comment by gr2m** [comment]
somehow our local setup got borked, I got the same error now. I think it's maybe due to a new selenium release, but the current setup only checks if `/tmp/sv-selenium` exists and if it does it assumes it can start selenium.

Try to `rm -rf /tmp/sv-selenium`, then `npm test` again

**Comment by zoepage** [comment]
I do not have a `/tmp` folder. 

Just saw, you copied the wd setup into the `test/test-init.js`, but as already mentioned, we do not use wb anymore. This is why we had the wdio.conf file.
