### ISSUE TITLE
demo is not working, the displayed format doesn't update

### ISSUE THREAD

**Issue by gr2m** [gr2m/smartdate-input#2]
http://gr2m.github.io/bootstrap-smartdate-input/

**Comment by zoepage** [comment]
I've tried it several times. Every time a format can't be parsed, it does not update.
Should we just display an error message here or colour the input red or something?

**Comment by gr2m** [comment]
I can't reproduce the issue myself, maybe it has been resolved meanwhile :) I'll create follow up issues if there are problems with specific formats, cheers

**Comment by zoepage** [comment]
Could finally reproduce the issue. The displayed format just does not update, when you click on the examples. If you change manually in the input, it works.

**Comment by gr2m** [comment]
Gotcha, confirmed

**Comment by zoepage** [comment]
issue here is the change:format event isn't fired, b/c the input is sorted as timestamp.

**Comment by gr2m** [comment]
closed via https://github.com/gr2m/smartdate-input/pull/7
