### ISSUE TITLE
semantic-release setup

### ISSUE THREAD

**Issue by zoepage** [gr2m/smartdate-input#4]
Could you please set up the semantic release here @gr2m ?
Thank you :)

**Comment by gr2m** [comment]
I need a test first :) But could be as simple as running `"test": "standard"` in package.json, just make sure bower_components gets ignored

**Comment by zoepage** [comment]
okay :) will ping, if done!

**Comment by zoepage** [comment]
@gr2m #5 :)

**Comment by zoepage** [comment]
@gr2m this can be closed right?

**Comment by gr2m** [comment]
yep
