### ISSUE TITLE
$('.input-lg').smartDate(options) not working correctly

### ISSUE THREAD

**Issue by gr2m** [gr2m/smartdate-input#9]
follow up for #6 

```js
$('.input-lg').smartDate({date: 'Fri Oct 16 2015 13:03:37 GMT+0200 (CEST)', format: 'DD MM YY'})
```

Does not set correct date

**Comment by gr2m** [comment]
@zoepage could you look into this issue next?

**Comment by zoepage** [comment]
Already did, as I already told. 
Will do again. But need working selenium setup for this.

**Comment by gr2m** [comment]
fixed via https://github.com/gr2m/smartdate-input/pull/36
